[container.image]
repository="continuous_integration"
name="Continuous-Integration-With-Azure-DevOps"
tag="v0.1.1"

[cloud.deployment]
min_memory="100Mi" 
max_memory="256Mi" 
min_cpu="1000m" 
max_cpu="1500m"
