name: Ballerina example
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
 
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action@master
        with:
          args:
            bal build --cloud=docker
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: target/docker/CICDSample
          push: true
          tags: user/cicd_sample:latest
